name: default
env:
  CGO_ENABLED: 0
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  gotest:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - run: go test -v ./...
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v2.1.2
